### ISSUE TITLE
Feedback on Substreams-powered subgraph developer experience

### ISSUE THREAD

**Issue by alex-pakalniskis** [ayechanst/hackathon#14]
Hey @ayechanst 

I'm Alex, a product manager working on subgraph development and indexer experience (if you stopped by The Graph booth at ETH Denver, I was the tall guy with the mask on).

I'd love to hear about your experience building a Substreams-powered subgraph (the good and the bad). 

Thanks and hope you are well,
Alex

**Comment by ayechanst** [comment]
hi! sorry this got away from me, it was good! the only thing that caused problems for my team and i were the store limits in the store modules. this prevented us from indexing the entire blockchain as we planned to, because the store modules kept blowing up. i think that was our only complaint, i was mostly working on the front end of our hackathon project.

**Comment by alex-pakalniskis** [comment]
Hey @ayechanst!

No worries at all. Thanks for getting back to me and appreciate the feedback. I'll share with the team internally.

Best,
Alex
